"""
Django settings for catalogapp project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # points to catalogapp/ root containing manage.py


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&u320^6_)6lnhutd(fj$q-nnoc&^*7)*x#b8sr8!m83um+cu-a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition


INSTALLED_APPS = [
     "jazzmin",   # 👈 add this
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

      # our app
    'catalogues',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'catalogapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'catalogapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Catalogue Admin",
    "site_header": "Catalogue Admin Panel",
    "welcome_sign": "Welcome to Catalogue Management",
    "site_brand": "Catalogue Portal",

    # 🎨 Red + White Theme
    "theme": "cosmo",  
    "primary_color": "#ff0000",   
    "secondary_color": "#ffffff", 
    "accent": "#ff0000",          
    "navbar": "#ff0000",          
    "navbar_classes": "navbar-dark",  
    "sidebar": "#ffffff",         
    "sidebar_hover": "#ff0000",   

    "button_classes": {
        "primary": "btn btn-danger text-white",  
        "secondary": "btn btn-light text-dark",  
    },
}

import os
STATIC_URL = '/static/'
# media (development)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# optional redirects
LOGIN_REDIRECT_URL = '/catalogues/'
LOGOUT_REDIRECT_URL = '/'

# Optional Jazzmin customization
JAZZMIN_SETTINGS = {
    "site_title": "Catalogue Admin",
    "site_header": "Catalogue Management System",
    "welcome_sign": "Welcome Admin",
    "theme": "cosmo",
}
# Testing configuration (for pytest-django)
import sys  # Add this if not already at the top (after 'from pathlib import Path')
if 'pytest' in sys.modules:
    import os
    os.environ['DJANGO_SETTINGS_MODULE'] = 'catalogapp.settings'
    DATABASES['default']['NAME'] = ':memory:'  # Use in-memory DB for faster tests