# Generated by Django 4.2.24 on 2025-10-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='pdf',
            field=models.FileField(upload_to='catalogues_pdfs/'),
        ),
    ]
