# Generated by Django 4.2.24 on 2025-10-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_alter_catalogue_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
